version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    container_name: actix_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 127.0.0.1:${PG_EXPOSED_PORT:-0}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data